### ISSUE TITLE
help.rs suggests 'rustup install nightly-2014-12-18', which fails

### ISSUE THREAD

**Issue by cxbrooks** [rust-lang-nursery/rustup.rs#787] opened 2016-10-29 04:35 UTC
rustup toolchain help

says

> 'channel' is either a named release channel or an explicit version
> number, such as '1.8.0'. Channel names can be optionally appended with
> an archive date, as in 'nightly-2014-12-18', in which case the
> toolchain is downloaded from the archive for that date.

However:

```
cxh@swarmnuc001:~$ rustup install nightly-2014-12-18
info: syncing channel updates for 'nightly-2014-12-18-x86_64-unknown-linux-gnu'
error: no release found for 'nightly-2014-12-18'
cxh@swarmnuc001:~$ 
```

This happens for me under Mac OS X El Capitan, RHEL 6.x and Ubuntu 14.x

`rustup install nightly-2015-03-01`

works and seems to install a 1.0.0 version.

Probably the thing to do is to modify  rustup.rs/src/rustup-cli/help.rs to use a date that works.

**Comment by cardoe** [comment] 2016-11-23 15:38
Likely a duplicate of #761.

**Comment by Diggsey** [comment] 2017-05-10 10:29
Fixed

**Closed by Diggsey** 2017-05-10 10:29 UTC
Labels: easy, help wanted
