### ISSUE TITLE
rustup toolchain uninstall: entered unrechable code

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustup.rs#504] opened 2016-05-30 11:54 UTC
I was trying to remove a toolchain, and saw this:

```
$ rustup toolchain uninstall nightly
thread '<main>' panicked at 'internal error: entered unreachable code', src/rustup-cli/rustup_mode.rs:42
note: Run with `RUST_BACKTRACE=1` for a backtrace.
```

`rustup toolchain remove` works though.

This is with

```
$ rustup --version
rustup 0.1.12 (c6e430a 2016-05-12)
```

**Comment by peschkaj** [comment] 2016-05-30 13:14
This is a duplicate of #474 and should be fixed in the next release.

**Closed** 2016-05-30 13:19 UTC
