### ISSUE TITLE
Confusing error message when specifying non-existent version

### ISSUE THREAD

**Issue by kamalmarhubi** [rust-lang-nursery/rustup.rs#793] opened 2016-11-04 01:02 UTC
The following interaction is confusing:

```
$ rustup run 1.8 rustc test.rs
error: toolchain '1.8' is not installed
$ rustup install 1.8
error: toolchain '1.8' is not installed
$ rustup install 1.8.0
info: syncing channel updates for '1.8.0-x86_64-unknown-linux-gnu'

  1.8.0-x86_64-unknown-linux-gnu unchanged - rustc 1.8.0 (db2939409 2016-04-11)
```

The second error should say that `1.8` isn't even a thing, not that it's not installed. The first probably should as well. Bonus points for suggesting `1.8.0`, especially if it's installed as is the case here.

**Comment by Diggsey** [comment] 2017-05-04 22:01
Dupe of #301

**Closed by Diggsey** 2017-05-04 22:01 UTC
Labels: bug, help wanted
