### ISSUE TITLE
Unable to install rust-src component on Windows 8.1

### ISSUE THREAD

**Issue by jarcane** [rust-lang-nursery/rustup.rs#760] opened 2016-10-15 16:03 UTC
I installed rustup today with the intent of making it easier to set up all the component bits for racer and so on, but I'm having trouble installing the rust-src component. I get this every time:

![](https://pbs.twimg.com/media/Cu0eQR7XEAA7FmK.jpg:large)

I've tried this on both user and admin access, and same error either way.

Running: Windows 8.1, rustup 0.6.3 (a0e2132 2016-08-28), rustc stable-x86_64-pc-windows-msvc 1.12.0 (3191fbae9 2016-09-23), cargo 0.13.0-nightly (109cb7c 2016-08-19).

**Comment by bakirov** [comment] 2016-10-22 05:38
If you have an antivirus software, you may need to turn it off and try again. But before, you have to remove previous `src` directory.

**Comment by Diggsey** [comment] 2017-05-03 23:44
Dupe of #771

**Closed by Diggsey** 2017-05-03 23:44 UTC
