### ISSUE TITLE
Command to get toolchain path

### ISSUE THREAD

**Issue by alexreg** [rust-lang-nursery/rustup.rs#491] opened 2016-05-23 00:19 UTC
The old `multirust` (script) had a `ctl` command that allowed you to get the default toolchain, active toolchain, and path for any given toolchain. Is there a way to do this in rustup? If not, it would be a nice feature to add, for scripting in particular.

**Comment by brson** [comment] 2016-06-03 21:20
There's no way to do this presently. `ctl` was an implementation detail of multirust and I didn't expect it to be used for scripting. If you want the active toolchain path you can run `rustup which rustc` and derive it from that. If you need more precise information I'm interested to know what exactly and for what purpose.

**Comment by alexreg** [comment] 2016-06-03 23:41
Yeah, that’s the solution I was considering. My use case was actually for a script for viewing Rust man pages for the current toolchain.

**Comment by Diggsey** [comment] 2017-05-04 18:17
Dupe of #450

**Closed by Diggsey** 2017-05-04 18:17 UTC
