### ISSUE TITLE
Sanity check that rustup is actually invoking the rustc it expects

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#506] opened 2016-05-31 16:13 UTC
The way rustup sets up the environment allows the system to override which rustc is invoked, which can really break the users expectations. As long as the environment is set up this way, we should probably do a sanity check during `rustup which` (or elsewhere) that the compiler invoked is the one we expect.

I might be more inclined to change the way the environment is configured (again), to make sure rustup runs the compiler it expects.

cc @briansmith

**Comment by Diggsey** [comment] 2017-05-04 21:07
Dupe of #159

**Closed by Diggsey** 2017-05-04 21:07 UTC
