### ISSUE TITLE
Show the previous version after update or provide a log

### ISSUE THREAD

**Issue by hgrecco** [rust-lang-nursery/rustup.rs#417] opened 2016-05-07 22:12 UTC
This is a minor suggestion. I have just updated using rustup and got something like:

```
   stable updated - rustc 1.8.0 (db2939409 2016-04-11)
     beta updated - rustc 1.9.0-beta.2 (87cb73304 2016-05-04)
  nightly updated - rustc 1.10.0-nightly (62e2b2fb7 2016-05-06)
```

While I know which minor version I was using for stable, I do not really remember exactly which beta and nightly was I using (and it might be useful to debug something which is not compiling)

It might be nice to show the previous version after update. Something like this:

```
   stable updated - rustc 1.8.0 (db2939409 2016-04-11)
             previous - rustc <version> (<commit>  <date>)
     beta updated - rustc 1.9.0-beta.2 (87cb73304 2016-05-04)
            previous - rustc <version> (<commit>  <date>)
  nightly updated - rustc 1.10.0-nightly (62e2b2fb7 2016-05-06)
             previous - rustc <version> (<commit>  <date>)
```

or have a log:

```
$ rustup log
2016-05-11 19:01:32 - stable updated - rustc 1.8.0 (db2939409 2016-04-11)
2016-05-11 19:01:32 - beta updated - rustc 1.9.0-beta.2 (87cb73304 2016-05-04)
2016-05-11 19:01:32 - nightly updated - rustc 1.10.0-nightly (62e2b2fb7 2016-05-06)
2016-02-01 10:39:45 - stable updated - <version> (<commit>  <date>)
2016-02-01 10:39:45 - beta updated - <version> (<commit>  <date>)
2016-02-01 10:39:45 -  nightly updated - <version> (<commit>  <date>)
```

**Comment by donhcd** [comment] 2016-11-30 23:51
after updating my nightly, something stopped compiling properly. Ideally I'd be able to revert to my original nightly so that I could compare the behavior and try to figure out how to fix it

**Comment by Diggsey** [comment] 2017-05-04 20:53
Dupe of #217

**Closed by Diggsey** 2017-05-04 20:53 UTC
