### ISSUE TITLE
Make installation location more configurable.

### ISSUE THREAD

**Issue by brson** [rust-lang-nursery/rustup.rs#194] opened 2016-03-29 20:11 UTC
Right now you can override CARGO_HOME to change where installation is going to be, but this is not discoverable. Furthermore, just installing to a different CARGO_HOME is not sufficient if you want the installation to actually work because cargo needs to be able to find it. So installing to alternate locations probably needs to set CARGO_HOME globally.

Also, if we do this it probably needs to configure `RUSTUP_HOME`.

**Comment by Diggsey** [comment] 2017-05-04 20:59
Dupe of #618

**Closed by Diggsey** 2017-05-04 20:59 UTC
