### ISSUE TITLE
rustup update nightly fails

### ISSUE THREAD

**Issue by TimNN** [rust-lang-nursery/rustup.rs#268] opened 2016-04-05 14:57 UTC
On OS X:
```sh
> rustup --version
rustup 0.1.3
> rustup toolchain list
nightly
nightly-2016-03-26
nightly-2016-03-26-x86_64-apple-darwin
nightly-2016-04-02-x86_64-apple-darwin
nightly-x86_64-apple-darwin
stable
> rustup --verbose update nightly
verbose: read metadata version: '12'
verbose: updating existing install for 'nightly-x86_64-apple-darwin'
verbose: toolchain directory: '/Users/logic/.multirust/toolchains/nightly-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-x86_64-apple-darwin'
verbose: creating temp file: /Users/logic/.multirust/tmp/umkvy9x4hmpu77ck_file
verbose: downloading file from: 'https://static.rust-lang.org/dist/channel-rust-nightly.toml.sha256'
verbose: deleted temp file: /Users/logic/.multirust/tmp/umkvy9x4hmpu77ck_file
verbose: creating temp file: /Users/logic/.multirust/tmp/uo7vqtorg5gcyg9f_file.toml
verbose: downloading file from: 'https://static.rust-lang.org/dist/channel-rust-nightly.toml'
verbose: checksum passed
verbose: deleted temp file: /Users/logic/.multirust/tmp/uo7vqtorg5gcyg9f_file.toml
error: manifest missing package for component rust-std-aarch64-unknown-linux-gnu
> rustup --verbose update nightly-2016-04-05                                                                                                                           
verbose: read metadata version: '12'
verbose: installing toolchain 'nightly-2016-04-05-x86_64-apple-darwin'
verbose: toolchain directory: '/Users/logic/.multirust/toolchains/nightly-2016-04-05-x86_64-apple-darwin'
info: syncing channel updates for 'nightly-2016-04-05-x86_64-apple-darwin'
verbose: creating temp file: /Users/logic/.multirust/tmp/cs6suxkfhg3s8fir_file
verbose: downloading file from: 'https://static.rust-lang.org/dist/2016-04-05/channel-rust-nightly.toml.sha256'
verbose: deleted temp file: /Users/logic/.multirust/tmp/cs6suxkfhg3s8fir_file
verbose: no update hash at: '/Users/logic/.multirust/update-hashes/nightly-2016-04-05-x86_64-apple-darwin'
verbose: creating temp file: /Users/logic/.multirust/tmp/v8c4gqhcjbck3e1w_file.toml
verbose: downloading file from: 'https://static.rust-lang.org/dist/2016-04-05/channel-rust-nightly.toml'
verbose: checksum passed
verbose: deleted temp file: /Users/logic/.multirust/tmp/v8c4gqhcjbck3e1w_file.toml
error: manifest missing package for component rust-std-aarch64-unknown-linux-gnu
```

**Comment by plumenator** [comment] 2016-04-05 15:39
Just encountered the same error on Ubuntu

**Comment by Bobo1239** [comment] 2016-04-05 15:46
Can confirm on windows and linux.

**Comment by alexcrichton** [comment] 2016-04-05 16:30
This was caused by https://github.com/rust-lang/rust-buildbot/commit/70357d92999698b7ec6224a84a80adea2dd41d59, fixed in https://github.com/rust-lang/rust-buildbot/commit/d4319e072ca207672fd10065f1aee01cee4069e3, and should be ready by tomorrow night.

In either case, though, seems like rustup should be resilient to slightly malformed manifests?

**Comment by brson** [comment] 2016-04-05 23:28
@alexcrichton This check is to explicitly to guard against the servers producing incorrect manifests (and it worked!).

For this particular check we might instead silently note that the component is busted and pretend it doesn't exist (if it's optional). If a required component is broken then that's a really bad error.

**Comment by brson** [comment] 2016-04-05 23:29
We could also run the rustup manifest validator, such as it is, on the server before deploying.

**Comment by alexcrichton** [comment] 2016-04-06 00:22
Ah yeah a validator is probably the best way to go here.

**Comment by pravic** [comment] 2016-04-06 10:29
Same here with Windows:
`
>rustup update nightly-x86_64-pc-windows-msvc
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
error: manifest missing package for component rust-std-aarch64-unknown-linux-gnu
`

**Comment by mattico** [comment] 2016-04-06 17:33
It's working for me now (must've built a new nightly).

**Comment by brson** [comment] 2016-04-06 17:51
In the meantime I'm going to change this error to more clearly indicate this isn't an end-user problem.

**Comment by peschkaj** [comment] 2016-05-02 14:28
triage - @brson I think this can be closed.

**Closed** 2016-05-02 14:29 UTC

**Comment by KodrAus** [comment] 2017-02-26 02:01
I'm getting this error for `nightly` today. In a fresh `ubuntu` container:

```shell
$ curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly
info: downloading installer
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
error: server sent a broken manifest: missing package for component rust-analysis-aarch64-apple-ios
info: caused by: package not found: 'rust-analysis'
rustup: command failed: /tmp/tmp.fPP2ubNCWO/rustup-init -y --default-toolchain nightly
```

`stable` seems to be fine.

**Comment by FaultyRAM** [comment] 2017-02-26 03:42
Getting it on Windows 10 Pro x64 1607 as well:

```txt
PS C:\Users\FaultyRAM> rustup --verbose update
verbose: read metadata version: '12'
verbose: updating existing install for 'nightly-x86_64-pc-windows-msvc'
verbose: toolchain directory: 'C:\Users\FaultyRAM\.rustup\toolchains\nightly-x86_64-pc-windows-msvc'
info: syncing channel updates for 'nightly-x86_64-pc-windows-msvc'
verbose: creating temp file: C:\Users\FaultyRAM\.rustup\tmp\grm_04yq8kfb9364_file
verbose: downloading file from: 'https://static.rust-lang.org/dist/channel-rust-nightly.toml.sha256'
verbose: downloading with curl
verbose: deleted temp file: C:\Users\FaultyRAM\.rustup\tmp\grm_04yq8kfb9364_file
verbose: creating temp file: C:\Users\FaultyRAM\.rustup\tmp\7f5qejt2hto7k70z_file.toml
verbose: downloading file from: 'https://static.rust-lang.org/dist/channel-rust-nightly.toml'
verbose: downloading with curl
verbose: checksum passed
verbose: deleted temp file: C:\Users\FaultyRAM\.rustup\tmp\7f5qejt2hto7k70z_file.toml
error: server sent a broken manifest: missing package for component rust-analysis-aarch64-apple-ios
info: checking for self-updates

  nightly-x86_64-pc-windows-msvc update failed - rustc 1.17.0-nightly (306035c21 2017-02-18)
```

**Comment by bitbegin** [comment] 2017-02-26 06:03
```
PS C:\Users\Administrator\.cargo\bin> rustup --verbose update
verbose: read metadata version: '12'
verbose: updating existing install for 'stable-i686-pc-windows-gnu'
verbose: toolchain directory: 'C:\Users\Administrator\.rustup\toolchains\stable-i686-pc-windows-gnu'
info: syncing channel updates for 'stable-i686-pc-windows-gnu'
verbose: creating temp file: C:\Users\Administrator\.rustup\tmp\tnvi1j4aajdot318_file
verbose: downloading file from: 'https://static.rust-lang.org/dist/channel-rust-stable.toml.sha256'
verbose: downloading with curl
verbose: deleted temp file: C:\Users\Administrator\.rustup\tmp\tnvi1j4aajdot318_file
verbose: toolchain is already up to date
verbose: updating existing install for 'nightly-i686-pc-windows-gnu'
verbose: toolchain directory: 'C:\Users\Administrator\.rustup\toolchains\nightly-i686-pc-windows-gnu'
info: syncing channel updates for 'nightly-i686-pc-windows-gnu'
verbose: creating temp file: C:\Users\Administrator\.rustup\tmp\mhwfnsbhn86w7qva_file
verbose: downloading file from: 'https://static.rust-lang.org/dist/channel-rust-nightly.toml.sha256'
verbose: downloading with curl
verbose: deleted temp file: C:\Users\Administrator\.rustup\tmp\mhwfnsbhn86w7qva_file
verbose: creating temp file: C:\Users\Administrator\.rustup\tmp\hzag9llf5qhjktr5_file.toml
verbose: downloading file from: 'https://static.rust-lang.org/dist/channel-rust-nightly.toml'
verbose: downloading with curl
verbose: checksum passed
verbose: deleted temp file: C:\Users\Administrator\.rustup\tmp\hzag9llf5qhjktr5_file.toml
error: server sent a broken manifest: missing package for component rust-analysis-aarch64-apple-ios
info: checking for self-updates

  stable-i686-pc-windows-gnu unchanged - rustc 1.15.1 (021bd294c 2017-02-08)
  nightly-i686-pc-windows-gnu update failed - rustc 1.11.0-nightly (bb4a79b08 2016-06-15)
```

**Comment by gbip** [comment] 2017-02-26 09:40
I have the same problem :
```
 
⇒  rustup update 
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
error: server sent a broken manifest: missing package for component rust-analysis-aarch64-apple-ios
info: checking for self-updates

       stable-x86_64-unknown-linux-gnu unchanged - rustc 1.15.1 (021bd294c 2017-02-08)
  nightly-x86_64-unknown-linux-gnu update failed - rustc 1.17.0-nightly (668864d9e 2017-02-16)
```

**Comment by KodrAus** [comment] 2017-02-26 10:14
@alexcrichton linked this patch as a fix in another issue: https://github.com/rust-lang/rust/pull/40111
