### ISSUE TITLE
Add more info in "rustup update"

### ISSUE THREAD

**Issue by reverendhomer** [rust-lang-nursery/rustup.rs#680] opened 2016-08-23 12:34 UTC
It would be much easier to understand what toolchain you are updating. When I saw this output during update

```
$ rustup update
info: syncing channel updates for 'stable-x86_64-unknown-linux-gnu'
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
info: downloading component 'rustc'
 49.0 MiB /  49.0 MiB (100 %)   5.4 MiB/s ETA:   0 s                
info: downloading component 'rust-std'
 61.9 MiB /  61.9 MiB (100 %)   4.4 MiB/s ETA:   0 s                
info: downloading component 'rust-docs'
  8.4 MiB /   8.4 MiB (100 %)   2.0 MiB/s ETA:   0 s                
info: downloading component 'cargo'
  4.2 MiB /   4.2 MiB (100 %)   1.4 MiB/s ETA:   0 s                
info: installing component 'rustc'
info: installing component 'rust-std'
info: installing component 'rust-docs'
info: installing component 'cargo'
info: checking for self-updates
info: downloading self-update

  stable-x86_64-unknown-linux-gnu unchanged - rustc 1.11.0 (9b21dcd6a 2016-08-15)
   nightly-x86_64-unknown-linux-gnu updated - rustc 1.13.0-nightly (1576de0ce 2016-08-21)
```

I was confused, because it isn't so obvious that rustup was updating nightly toolchain.

Can you add one simple string which will inform, for example, "Updating 'nightly-x86_64-unknown-linux-gnu'", please?

**Comment by Diggsey** [comment] 2017-05-04 00:28
Dupe of #1007

**Closed by Diggsey** 2017-05-04 00:28 UTC
