### ISSUE TITLE
Cargo bin's not added to PATH 

### ISSUE THREAD

**Issue by gnzlbg** [rust-lang-nursery/rustup.rs#535] opened 2016-06-16 13:48 UTC
I'm using the fish shell under MacOS X Capitan and after using rustup.rs I get the following message:

```shell
Rust is installed now. Great!

To get started you need Cargo's bin directory in your PATH environment variable.
Next time you log in this will be done automatically.
```

The next time I logged in Cargo was not in my PATH. I had to add it manually. 

In my `.config/config/fish.config` file I have a:

> set -x PATH ...

line where I had to manually add cargo bin's:

> set -x PATH ... .cargo/bin

**Comment by brson** [comment] 2016-06-23 23:44
Thanks for the report. Yep, rustup doesn't know how to deal with fish shell. This is a duplicate of either https://github.com/rust-lang-nursery/rustup.rs/issues/478 or https://github.com/rust-lang-nursery/rustup.rs/issues/371.

**Closed by brson** 2016-06-23 23:44 UTC

**Comment by alper** [comment] 2020-11-05 10:34
So what's the solution?

**Comment by kinnison** [comment] 2020-11-06 09:00
You can find fish help in #478 I think

**Comment by polyglotdev** [comment] 2022-03-12 17:44
1.  Run the `fish_add_path` command like 👇🏾
```bash
fish_add_path /home/your-username/.cargo/bin/
```
2. Restart your shell
3. Check out more information from [fish-shell docs](https://fishshell.com/docs/current/cmds/fish_add_path.html)

**Comment by polyglotdev** [comment] 2022-03-12 17:46
I think it is also worth noting that if you are using fish sticking configuration in your `.zshrc` is only going to complicate things, so my suggestion would be if it needs to be sourced into your env, use the fish commands.
