### ISSUE TITLE
Fail uninstalling toolchain in windows

### ISSUE THREAD

**Issue by danslapman** [rust-lang-nursery/rustup.rs#492] opened 2016-05-23 18:58 UTC
Hi! Currently, I have two toolchains installed:
`installed toolchains

stable-i686-pc-windows-gnu
stable-x86_64-pc-windows-gnu (default)

active toolchain

stable-x86_64-pc-windows-gnu (default)
rustc 1.8.0 (db2939409 2016-04-11)`

When i type `rustup toolchain uninstall stable-i686-pc-windows-gnu`, I get this error:
`thread '<main>' panicked at 'internal error: entered unreachable code', src/rustup-cli\rustup_mode.rs:42
note: Run with`RUST_BACKTRACE=1`for a backtrace.`

**Comment by peschkaj** [comment] 2016-05-24 18:30
I believe this is a duplicate of https://github.com/rust-lang-nursery/rustup.rs/issues/465

**Comment by brson** [comment] 2016-06-03 21:16
Closing as dupe. This will be fixed in the next release (not sure when it'll be out). In the meantime, `rustup toolchain remove` works.

**Closed** 2017-05-04 17:35 UTC
