### ISSUE TITLE
Colours in rustup output are not meant to be used in a white background

### ISSUE THREAD

**Issue by hfiguiere** [rust-lang-nursery/rustup.rs#789] opened 2016-10-31 20:52 UTC
My terminal prints black on a white background. On of the coloured messages from rustup installation is too light of a gray to be readable on white. See the screenshot:

![screenshot from 2016-10-31 16-51-23](https://cloud.githubusercontent.com/assets/114441/19871200/4a033976-9f8a-11e6-9775-b2a7b3f24bef.png)

Solution:
* use a darker colour

**Comment by hfiguiere** [comment] 2016-10-31 20:53
"Welcome to Rust!" as well at the top. I didn't even see it. (same colour)

**Comment by Diggsey** [comment] 2017-05-04 18:24
Dupe of #433

**Closed by Diggsey** 2017-05-04 18:24 UTC
