### ISSUE TITLE
Fetch rust sources when install toolchain. (for racer)

### ISSUE THREAD

**Issue by aka-demik** [rust-lang-nursery/rustup.rs#505] opened 2016-05-31 07:51 UTC
Now we have to do it manually.

**Comment by thommay** [comment] 2016-05-31 13:15
Dependent on https://github.com/rust-lang/rust-buildbot/pull/102 (since I just went looking to solve this)

**Comment by Diggsey** [comment] 2016-05-31 13:17
Duplicate of #37

**Closed by Diggsey** 2016-05-31 13:17 UTC
