### ISSUE TITLE
Installation successful message difficult to see on light background

### ISSUE THREAD

**Issue by leahscampoli** [rust-lang-nursery/rustup.rs#654] opened 2016-08-13 19:03 UTC
The installation message ("Rust is installed now. Great!") is hard to see on a white background.

For instance, on the default Mac Terminal, the grey text used is very hard to see.

Screenshot:

<img width="567" alt="screen shot 2016-08-13 at 12 02 12 pm" src="https://cloud.githubusercontent.com/assets/17069488/17645019/d0d503e2-614d-11e6-86bf-6cddebccc7c5.png">

**Comment by Diggsey** [comment] 2017-05-04 00:40
Dupe of #789

**Closed by Diggsey** 2017-05-04 00:40 UTC
