### ISSUE TITLE
invalid(?) toolchain specification confuses rustup

### ISSUE THREAD

**Issue by durka** [rust-lang-nursery/rustup.rs#751] opened 2016-10-10 17:55 UTC
Specifying a toolchain version that rustup doesn't recognize seems to do the wrong thing.

Installation:

``` sh
$ rustup update 1.8
error: toolchain '1.8' is not installed # I know, that's what I was trying to change!
$ rustup update 1.8.0
info: syncing channel updates for '1.8.0-x86_64-apple-darwin' # OK
...
```

Running:

``` sh
$ rustup run 1.8 rustc -V
error: toolchain '1.8' is not installed # but I just installed 1.8.0!
$ rustup run 1.8 cargo script -e 1
error: toolchain '1.8' is not installed # expected e.g. "unrecognized toolchain version"
info: caused by: not a directory: '/Users/alex/.multirust/toolchains/1.8' # WAT
internal error: cargo failed with status 1 # why did you run cargo if it's not installed‽‽
$ rustup run 1.8.0 cargo script -e 1
   Compiling expr v0.1.0 (file:///Users/alex/.cargo/.cargo/script-cache/expr-356a192b7913b04c)
1 # OK
```

**Comment by Diggsey** [comment] 2017-05-03 23:50
Dupe of #793

**Closed by Diggsey** 2017-05-03 23:50 UTC
