### ISSUE TITLE
rustup should verify paths 

### ISSUE THREAD

**Issue by dashed** [rust-lang-nursery/rustup.rs#576] opened 2016-07-12 03:53 UTC
I think it'll be nice for rustup to verify paths and the right version combo of cargo and rustc is available.

**Comment by brson** [comment] 2016-07-19 18:20
Thanks for the report @dashed.

Can you expand on your suggestion? Which paths should be verified and when?

**Comment by dashed** [comment] 2016-07-20 17:55
To elaborate, I was wondering if rustup would be able to verify/check that `rustc` and/or `cargo` commands point to the right versions/paths. 

------

I ran into an issue where the cargo I was using was not the one that rustup installed (which might be leftover from multirust or something).

**Comment by brson** [comment] 2016-07-26 01:13
Thanks for the clarification.

I think rustup used to have a check like that (cc @Diggsey). ISTR that I removed it because it assumed that the `PATH` was configured such that `rustup` and `cargo` could both be executed without explicit paths, and that assumption is not required by the implementation. One is perfectly welcome not to configure `PATH` and run e.g. `cargo` as `~/.cargo/bin/cargo`. In that scenario rustup can't assume anything about what the plain `cargo` command is.

**Comment by Diggsey** [comment] 2016-07-26 09:49
@brson It used to warn whenever it was run that the PATH wasn't set up correctly - perhaps we could instead add a subcommand like `detect-problems`, which can be used manually, but also automatically runs post-install, and just warns about any potential issues, and suggests ways to fix them if they're not intentional?

**Comment by brson** [comment] 2016-07-26 20:15
@Diggsey yeah that sounds good. I know I've had several sanity checks in mind, and there are a few scattered about already.

**Comment by Diggsey** [comment] 2017-05-05 22:04
Dupe of #159

**Closed by Diggsey** 2017-05-05 22:04 UTC
Labels: enhancement
