### ISSUE TITLE
x.y is not a valid version for toolchain install

### ISSUE THREAD

**Issue by nagisa** [rust-lang-nursery/rustup.rs#554] opened 2016-07-01 16:37 UTC
took me a while to figure out I need version in x.y.z format.

**Comment by brson** [comment] 2016-07-08 17:04
As with some other features, this will require an index of all releases on the server to make work.

A related issue is that rustup doesn't ever do any fuzzy matching on semver - all versions are exact. This will become an important matter when Rust makes its first stable point release. There will probably be a reasonable expectation that rustup upgrades from X.Y.0 to X.Y.1 automatically.

**Comment by steveklabnik** [comment] 2016-07-08 17:44
Also, it's worth noting that the semver spec is a bit murky around `x.y` being equivalent to `x.y.z`, so the semver crate doesn't parse it as a version. There's [a PR](https://github.com/steveklabnik/semver-parser/pull/2) for it, but I haven't decided if I want to merge it or not.

**Comment by Diggsey** [comment] 2017-05-04 01:05
Dupe of #794

**Closed by Diggsey** 2017-05-04 01:05 UTC
