### ISSUE TITLE
Trying to set nightly override gives checksum failed error

### ISSUE THREAD

**Issue by est31** [rust-lang-nursery/rustup.rs#507] opened 2016-06-01 13:41 UTC
See error below. 

```
$ rustup override set nightly
info: syncing channel updates for 'nightly-x86_64-unknown-linux-gnu'
error: checksum failed, expected: '9067209d6e8cb582b1f0b88f6a3371021452765b503228a614b187a33b395a6e', calculated: '816f945f87a661310941b40697321b048325ccbaf78b8d92841e755051642a5b'
```

The rustup version is `rustup 0.1.12 (c6e430a 2016-05-12)`, the latest one that `rustup self update` gives me.

**Comment by est31** [comment] 2016-06-03 20:49
Hmm it works again.

**Comment by brson** [comment] 2016-06-03 21:00
This is a known problem with out CDN. Sorry for the inconvenience. Considering this a dupe of https://github.com/rust-lang-nursery/rustup.rs/issues/346.

**Closed by brson** 2016-06-03 21:00 UTC
